### ISSUE TITLE
Blast 3D

### ISSUE THREAD

**Issue by angros47** [blitzcoder/CBase#1]
I have a question: is this project going to be part of Blast 3D? Which 3D engine is used for Blast 3D itself? Because from the screenshot and the description of some commands I have read on blitzcoder and from the demo I tried, I have the impression that the engine used is OpenB3D. Is that correct?

**Comment by blitzcoder** [comment]
Hey there @angros47. Happy New Year! 🎉

Yes, this is part of Blast3D and the 3D engine is OpenB3D.

Cheers.

**Comment by angros47** [comment]
Happy new year to you!
I am always glad to see someone using OpenB3D. Have you had to make any change to it, or are you using the version provided on github/sourceforge? I would be interested to hear any feedback, in case.

**Comment by blitzcoder** [comment]
Awesome. It became an obvious choice since it has history and closest to Blitz3D.

I'm still using v1.25 and will update to the latest eventually. 

Yes, I'd be happy to post some suggestions and feedback soon.
